FROM node:20-alpine

ARG HOST
ARG PORT
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_NAME
ARG JWT_SECRET


ENV HOST=$HOST
ENV PORT=$PORT
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_NAME=$DATABASE_NAME
ENV JWT_SECRET=$JWT_SECRET


COPY . /app

WORKDIR /app

RUN npm i && \
    npm uninstall bcrypt && \
    npm i bcrypt

EXPOSE 3000-3001

CMD npm start
